### ISSUE TITLE
Beam-center finder performance

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esssans#12]
There are a couple ways that may improve the performance of the beam-center finding:

1. Histogram after conversion to wavelength. In the Sans2d example (60 kPixel, 7 Mevents) this yielded a 2x speeup.
2. Only convert to wavelength once (and thus histogram once, if 1.) is also used). This is an approximation, but the small x/y shifts should have only secondary influence on L2, so maybe this ok? Would need to be tested in practice.

We will need to try this for more realistic LoKI data, so we see whether this matters in practice, and which options work best.

**Comment by SimonHeybrock** [comment]
If #16 can be used in practice (much faster by just using center-of-mass) then this may be mostly obsolete. Time will tell.

**Comment by jokasimr** [comment]
Do we have any data with a ground-truth beam center to compare the accuracy of the two methods?

A third option is to use the curve-fit routine to estimate the center of the beam. It's probably less time consuming than the optimization based beam-center-finder, and it might be less biased than the center-of-mass beam-center-finder.

**Comment by SimonHeybrock** [comment]
I will close this, as there is little crucial/useful information in here, and some things have been refactored since I wrote the original. As I understand now we might not need to find the beam center for every run anyway, since it may be reused if the detector was not moved.
