### ISSUE TITLE
Add tests for `Workflow` objects

### ISSUE THREAD

**Issue by nvaytet** [scipp/esssans#145]
Following #136, the main way to perform a reduction is to use the `Workflow` objects (e.g. `Sans2dTutorialWorkflow`).
We have kept the old unit tests that work on the `Pipeline` and `providers`, but we should also test the workflow wrappers.

This is probably not much more than ensuring all the default parameters are set up correctly?

**Comment by SimonHeybrock** [comment]
Recent refactoring kind of did this implicitly --- most test now create pipelines using the pre-defined workflows.
