### ISSUE TITLE
Move ess notebook on beam center finder

### ISSUE THREAD

**Issue by nvaytet** [scipp/esssans#37]
The notebook describing the procedure for the beam center finder in the [ess docs](https://scipp.github.io/ess/techniques/sans/sans-beam-center-finder.html) contains some useful information that should not be lost.

We should move this notebook over to `esssans`.
Right now, we only have a notebook in the `examples` section. We probably need to re-organise the docs a little?

**Comment by SimonHeybrock** [comment]
It also would need to be extended with the new method via the center of "mass".

**Comment by nvaytet** [comment]
Fixed in #72
