### ISSUE TITLE
Should beam center finder construct inner IofQ pipeline based on outer pipeline?

### ISSUE THREAD

**Issue by jokasimr** [scipp/esssans#39]
In  [the beam center_finder](https://github.com/scipp/esssans/blob/cc664ecf4cd6073192cb6a38a191d8c19a9a7df5/src/esssans/beam_center_finder.py#L157) we repeatedly compute IofQ in quadrants. This is done by constructing a sciline pipeline and calling `pipeline.compute(IofQ[...])`. This "inner" pipeline is a subgraph of "outer" pipeline.

Right now we construct this subgraph manually inside the beam center finder. I think this is both a bit cumbersome and error-prone. It would be better to take the outer graph, copy it and replace parts of it.
Then we would only need to change `MaskedData[SampleRun]]`, `NormWavelengthTerm[SampleRun]` and `BeamCenter` inside the beam center finder routine, instead of manually copying all required providers to the new pipeline.

Encountered this issue when working on #29 . (See [this](https://github.com/scipp/esssans/pull/29/commits/a88a54ce9073d7deba82019a10d46a614001ed40) for a bad example of how to solve the problem.) In the PR new parameters are added to the IofQ pipeline, for example `DetectorPixelShape[RunType]` per run type. These will also need to be part of the inner pipeline. We can add the new providers as requirements to the beam center finder and add those to the inner pipeline, but it doesn't seem practical if every time we add new components to the outer pipeline we need to remember to also add them in the beam center finder.

I'm not sure what the best solution is here. In principle the inner pipeline should depend on the pipeline it is part of, but maybe that is too complicated. For now it's probably best to just add the new providers as requirements to beam center finder. Maybe this should be converted to an issue in sciline instead.

**Comment by SimonHeybrock** [comment]
I don't think this is conceptually possible if we want to run the beam-center finder as part of a workflow?

Two brief answers (that may not fully satisfy your concern):

- If we drastically change a pipeline introducing new dependencies via updated types and dependencies we will always notice, since the graph in the beam-center finder will fail to build. This is rare (I hope), so I do not see this as a usability issue.
- It is not clear if the version of the beam-center finder that uses the IofQ pipeline will actually be used in practice. We have since added a much simpler and faster version which does not need it.

**Comment by jokasimr** [comment]
> I don't think this is conceptually possible if we want to run the beam-center finder as part of a workflow?

I don't see why it wouldn't be? Conceptually there's nothing particularly unusual about a workflow where one step of the workflow is to run the workflow repeatedly with different parameters until good parameters are found so that those can be used in the real workflow.

I think might be cases when we don't notice differences between the inner and outer version of the pipeline. Possibly there's one minor example of that in the current workflow. In the beam-center-finder pipeline (the "inner" pipeline) [we use](https://github.com/scipp/esssans/blob/cc664ecf4cd6073192cb6a38a191d8c19a9a7df5/src/esssans/beam_center_finder.py#L168) `UncertaintyBroadcastMode.upper_bound ` regardless of what is used in the outer pipeline. (Maybe this is intentional here?)
