### ISSUE TITLE
Workflow causes files to be loaded twice when transmission runs are not seperate?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esssans#46]
See:

https://github.com/scipp/esssans/blob/a21ff03845a0de37a35d222ddc4634b389f54650/docs/examples/sans2d.ipynb#L71-L74

The workflow will, I think, *not* detect that this is the same file and load it twice.

I think we need to do this mapping later, after loading, somehow.

Note how this is bypassed in the Zoom workflow.

**Comment by jokasimr** [comment]
How about adding a helper to Sciline to handle this (maybe common) usecase?

I'm thinking something like this:
```python
pl = sciline.Pipeline(
    sans.providers + sans.sans2d.providers,
    params=sans.sans2d.default_parameters,
)

pl[FileList[BackgroundRun]] = ['SANS2D00063159.hdf5']
pl.insert(sciline.identify(
    LoadedFileContents[TransmissionRun[BackgroundRun]],
    LoadedFileContents[BackgroundRun]
))
pl[FileList[SampleRun]] = ['SANS2D00063114.hdf5']
pl.insert(sciline.identify(
    LoadedFileContents[TransmissionRun[SampleRun]],
    LoadedFileContents[SampleRun]
))
```

The implementation of `sciline.identify` would look something like this:
```python
def identify(A: type, B: type):
    'Identifies the type A with the type B'
    def identity(b):
        return A(b)
    identity.__annotations__ = {'b': B, 'return': A}
    # We would have to give the new provider some properties so it shows up nicely in the visualizations and reprs
    identity.__name__ = f'same as {B}' 
    return identity
```

The advantage is that it would be very easy to do those kinds of substitutions without defining new provider functions.

A better ux for this would maybe be to add the method directly to `Pipelin` like this:
```python
pl.identify( ... )
```

**Comment by SimonHeybrock** [comment]
> How about adding a helper to Sciline to handle this (maybe common) usecase?

"maybe" is the key here: We should not act on "maybe", in general. I think features should not be added unless the is proven and *repeated* need. In particular since Sciline is still young we have to be very careful about adding new features, until we have a really well understood core and conceptual clarity.

Furthermore, in this case there is a trivial solution (using a simple helper function, as in the referenced Zoom workflow) which is (1) barely longer than what you propose (2) standard Python that anyone can remember, as opposed to something you have to know that it exists and lookup the syntax.

**Comment by jokasimr** [comment]
I agree it's good to be careful about adding extra api surface area. And maybe in this case this is a bit premature. On the other hand we do already have two examples where this is used (sans2d and loki). While the manual solution (creating a new provider) is quite simple I think the version proposed here does save effort, for example it would remove the need for the providers in the `esssans.isis.common` module.

But sure, let's wait a bit for now and see if this is actually a common need.

**Comment by SimonHeybrock** [comment]
> On the other hand we do already have two examples where this is used (sans2d and loki). 

This is one example, since it is the same workflow. The solution I used for Zoom can be moved to the top level, I think?
