### ISSUE TITLE
Gravity vector is needed even if gravity is not used to compute two_theta

### ISSUE THREAD

**Issue by nvaytet** [scipp/esssans#48]
In the conversion graph, we are [adding coordinates](https://github.com/scipp/esssans/blob/main/src/esssans/conversions.py#L161-L165) (cylindrical_x, cylindrical_y unit vectors) that are used to compute the `phi` angle which is then used to decompose the detector panel in phi quadrants to [compute the beam center](https://github.com/scipp/esssans/blob/main/src/esssans/beam_center_finder.py#L179).
Those make use of the direction of gravity to determine what is down.

This means that even if we don't want to apply gravity correction to the flight paths of the neutrons, we still need the gravity coordinate.
However, if we are only using the beam center finder based on the center of mass (as opposed to $I(Q)$ inside 4 quadrants), then we do not need the gravity vector at all, but the workflow will complain if the gravity vector is missing from the data.

We should probably improve the logic to only require the gravity vector if needed.

**Comment by nvaytet** [comment]
Gravity vector is actually needed because we need to know which way is down, so that we can apply beam center corrections perpendicular to the beam (which is horizontal).

**Comment by SimonHeybrock** [comment]
Have you checked if the workflow works (without gravity vector) without beam-center finder, i.e., when we set the beam center to hand?

**Comment by nvaytet** [comment]
> Have you checked if the workflow works (without gravity vector) without beam-center finder, i.e., when we set the beam center to hand?

Good idea, will do.

**Comment by nvaytet** [comment]
See https://github.com/scipp/esssans/pull/77/commits/6b116bc23f4a979d69f7a8b917a492192d6c3181
