### ISSUE TITLE
Separate file loading and merging of events

### ISSUE THREAD

**Issue by nvaytet** [scipp/esssans#49]
In #35, we are using a single `load_nexus` provider to load and potentially merge the event lists if multiple files are given as inputs.

If we would like to use the same pipeline for a different instrument, ideally we would want to change the loading code but re-use the event list merging code.
However, we cannot do this currently (we would have to copy the code over).

We should make these two things 2 separate steps in the pipeline.

**Comment by SimonHeybrock** [comment]
See also scipp/esspolarization#19

**Comment by nvaytet** [comment]
Fixed in #96 ?
