### ISSUE TITLE
Docs build issues with `isis.mantidio`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esssans#55]
Run `tox -e docs` to reproduce:
```
WARNING: [autosummary] failed to import esssans.isis.mantidio.
Possible hints:
* ImportError: 
* AttributeError: module 'esssans.isis' has no attribute 'mantidio'
* ModuleNotFoundError: No module named 'mantid'
```

Should we try to make this importable without Mantid after all?

**Comment by jl-wynen** [comment]
> Should we try to make this importable without Mantid after all?

What would be the goal? The docs still wouldn't build. We'd have to adjust the notebook to just do nothing if Mantid is not installed, I guess? Or disable the notebook in some other way (maybe in `conf.py`).

**Comment by SimonHeybrock** [comment]
Why would the docs not build? They are building right now, and if the module can be imported then the docstrings can be use by autodoc.

**Comment by jl-wynen** [comment]
As far as I can tell, mantidio is only imported in a notebook:
```
$ rg mantidio
docs/examples/zoom.ipynb
159:    "    import esssans.isis.mantidio\n",
165:    "    for provider in sans.isis.mantidio.providers:\n",
```
So we need mantid anyway to build the docs

**Comment by SimonHeybrock** [comment]
The notebook is written in a way that it works without Mantid. Please have a look at the first post in this thread, this issue is about the autosummary, for the API reference.
