### ISSUE TITLE
Run beam-center finding on current run instead of hard-coding to `SampleRun`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esssans#62]
Current implementation:

https://github.com/scipp/esssans/blob/5c239c4ae97efb6a2a2e576eaf9fb8990e05c853/src/esssans/beam_center_finder.py#L275-L285

and

https://github.com/scipp/esssans/blob/5c239c4ae97efb6a2a2e576eaf9fb8990e05c853/src/esssans/beam_center_finder.py#L44-L47

Should we change this to return `BeamCenter[RunType]` and replace `SampleRun` -> `RunType` everywhere?

Points to consider:
- We still want to be able to set the value of the beam center by hand. This would be more complicated if we had to do it for all possible run times. It would be easy to forget some of the run types, leading to inconsistent result.
- We might want to reduce a run that has no sample run. Could be solved by setting beam center by hand.

**Comment by nvaytet** [comment]
Does this mean that you would compute a beam center for `SampleRun` and `BackgroundRun`?
Could it be difficult to compute a reliable beam center on a background run if the signal is weak/noisy? I think typically the background run is recorded for less time than the sample run?

**Comment by SimonHeybrock** [comment]
According to the scientists they would typically compute the beam center once, instead of doing it all the time. But maybe this is just because it used to be so slow using the old software?

**Comment by SimonHeybrock** [comment]
I believe this is no longer relevant, will be closed by #153.
