### ISSUE TITLE
Split loading of monitors and detector data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esssans#82]
There are a couple reasons for this:

1. Increase opportunities for task-graph level parallelism.
2. If monitors are large, it may be helpful to avoid issues with memory.
3. Simplify handling of transmission runs, where we only want to load monitors. This would avoid having to worry about whether the transmission runs have detector data (which we would want to exclude from the load), or data-runs where we want to avoid loading the transmission monitor (if there is a separate transmission monitor).

Should also be considered in relation to #83.

**Comment by nvaytet** [comment]
Note that a first attempt at this was done when implementing the direct beam iterations.
It was however [reverted in favour of a load_nexus](https://github.com/scipp/esssans/pull/35/commits/95f1aef18f37b4e7ac60481f82e7dc6f915525ba#diff-4deee399edfbe1368eec3c758e019a47f2972d9ebecb15878be74a16451f6234L86) which loaded everything internally.

If I remember correctly, this was mostly for simplicity and clarity in the final task graph, but we did not rule out implementing this in the future.

**Comment by SimonHeybrock** [comment]
I have experiment with larger files today (up to about 1e9 in detector and monitor) and my conclusion was that we have to be more deliberate about dependencies in the graphs, such as avoiding keeping alive intermediates by using them in multiple places.

We actually have to also sit down and have a look at final meta data assembly, e.g., as implemented in https://github.com/scipp/essreflectometry/pull/27, as this potentially introduces long term "global" dependencies that result in keeping alive raw data longer than we want. @jl-wynen has already into some problem, I think, so we really have to sit down and figure out some guidelines/lessons.

**Comment by SimonHeybrock** [comment]
After some more thought, I believe we should also split loading "the rest" of the file: We need information such as chopper logs to be able to process either monitors or data, and there are probably also other examples such as determining slicing. So my suggestion is something like:

1. Load everything but monitors and detectors
2. Some pre-processing
3. Load
   - monitors
   - detectors

**Comment by SimonHeybrock** [comment]
Absorbed in #83.
