### ISSUE TITLE
Move coord transform code from ESSsans to ScippNeutron?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esssans#90]
When doing so, make sure to follow the good practices in ScippNeutron regarding preserving precision of inputs. For example, a float32 `tof` will result in float32 `wavelength` or `Q`. I believe the current implementation of conversions with gravity here do not handle this appropriately, i.e., we unintentionally convert to float64 in several places.

**Comment by SimonHeybrock** [comment]
Not yet used here (I think?), so I'll reopen for now?

**Comment by jl-wynen** [comment]
Thanks! I didn't know GH can close issues across projects.
